---
# Learning about Playbooks
- name: bootstrapping and new user creation
  hosts: raiders        # our group in our inventory
  gather_facts: no
  connection: ansible.builtin.ssh

  vars:
    newuser1: marian
    newuser2: belloq
    newuser3: willie
    newuser4: elsa

  tasks:

  - name: determine if python is installed
    ansible.builtin.raw: "python3 --version"
    register: results  # creates a new variable called "results"
    failed_when: false # never fails
    changed_when: false # never yellow


  # use the raw module
  - name: update apt with latest repo info
    ansible.builtin.raw: "apt update -y"
    become: yes
    when: results.rc != 0

  - name: install py3 and pip3 with ansible raw
    ansible.builtin.raw: "apt install -y python3-pip"
    become: yes
    when: results.rc !=0


  - name: create new group
    ansible.builtin.group:
      name: indymovies
      state: present
    become: yes

  - name: Add newuser1 to target hosts
    ansible.builtin.user:
      name: "{{ newuser1 }}"
      state: present
      group: indymovies
    become: yes

  - name: Add newuser2 to target hosts   
    ansible.builtin.user:
      name: "{{ newuser2 }}"
      state: present
      group: indymovies
    become: yes

  - name: add newuser3 to target hosts
    ansible.builtin.user:
      name: "{{ newuser3 }}"
      state: present
      group: indymovies
    become: yes

  - name: add newuser4 to target hosts
    ansible.builtin.user:
      name: "{{ newuser4 }}"
      state: present
      group: indymovies
    become: yes

